### ISSUE TITLE
Fix the overview / abstract 

### ISSUE THREAD

**Issue by Athinodoros** [teutzue/BlogEntry#1]
You don't mention what the problem was, the why it was a problem. 
The abstract should give you an idea on will follow in the blog.
So it is a good idea to follow the 4 sentence rule. 

As mentioned in the doc from the class: 

I try to have four sentences in my abstract.

-The first states the problem.
-The second states why the problem is a problem.
-The third is my startling sentence.
-The fourth states the implication of my startling sentence.

Or, phrased differently: (https://lemire.me/blog/rules-to-write-a-good-research-paper/)

-state the problem
-say why it is interesting
-say what your solution achieves
-say what follows from your solution.

**Comment by teutzue** [comment]
Problem: "how to deal with big amount of data in Neo4j, avoid RAM overflow, bottlenecks when it comes to aggregated and ordered data". This doesn't sound as a problem right? I think it says exactly the problem.

**Comment by teutzue** [comment]
fixed
