### ISSUE TITLE
Architecture of investigation

### ISSUE THREAD

**Issue by biggiejr** [teutzue/BlogEntry#2]
In my personal opinion, you do not totally follow the "Architecture of investigation" 

<img width="672" alt="snimka obrazovky 2017-12-12 o 13 29 18" src="https://user-images.githubusercontent.com/9032462/33884629-b6a02840-df40-11e7-9b6b-c7d2a3b34163.png">

As I understand your blog entry, you have some kind of abstract and then two paragraphs: 
 **Design constraints, alternatives and assumptions**, **Theoretical explanations**
which I consider as some kind of introduction, meanwhile your main part, evidence, respectively 
 **Design criteria, sample calculations and Simulations** is barely 1/3 of the entry.

As a last thing I would pinpoint conclusion, after you make simulations you say the difference between the queries however, I would present it more clearly that it is conclusion since if you take a brief look over the entry you cant find it easily.

Overall rating: 
Overview                                                                             9
Reliable Data from Credible Sources                                10
Design Constraints and Assumptions                               8
Theoretical Explanations                                                    8
Design Criteria, Sample Calculations and Simulations     7
Previous Work/ Future Work                                              6

**Comment by teutzue** [comment]
Hey man, our blog entry is based on the guidelines at this document: https://datsoftlyngby.github.io/soft2017fall/UFO/technicalreportrubric.pdf - "it is a checklist for things to look for". This is why you can see a different structure.
